import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar'
import { Sidebar } from './Sidebar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>

          <div className='flex'>
          <Sidebar/>
          <div className='w-screen h-screen'>
          <Navbar/>

            {children}           

            </div>  
          </div>



      </body>
    </html>
  )
}
